language: c

dist: trusty

addons:
  apt:
    packages:
    - libsdl2-dev
    - cmake-data
    - cmake
    - doxygen
    - graphviz

branches:
  only:
    - master
    

matrix:
  include:
  - os: linux
    compiler: gcc
    after_success:
    - make doc
    - cd html
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc
    before_install:
    - brew update
    - brew install
        sdl2
  - os: osx
    compiler: clang
    before_install:
    - brew update
    - brew install
        sdl2


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GithubDocsToken
  #local_dir: html/
  on:
    branch: master
    os: linux
    compiler: gcc
before_script:
    - if [[ "$BUILD" == "native" ]]; then
      $CC --version;
      cmake --version;
      sdl2-config --version;
      fi
    - mkdir build
    - cd build
    - cmake -DSDL_gpu_BUILD_DEMOS=ON -DSDL_gpu_BUILD_TESTS=ON -DSDL_gpu_BUILD_TOOLS=ON -DSDL_gpu_BUILD_SHARED=ON -DSDL_gpu_BUILD_STATIC=ON ..

script: make